version: "3"

services:
  db:
    image: mariadb:11.1
    container_name: project-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_bweng
      MYSQL_USER: user
      MYSQL_PASSWORD: pw
    ports:
      - "3306:3306"